# $NetBSD$

DISTNAME=	scroll-0.1
CATEGORIES=	# TODO: add primary category
MASTER_SITES=	https://dl.suckless.org/tools/

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE # or use pkgsrc-users@NetBSD.org
HOMEPAGE=	https://dl.suckless.org/tools/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)


MAKE_FLAGS+=	PREFIX=${PREFIX}
MAKE_FLAGS+=	MANDIR=${PREFIX}/man

.include "../../mk/bsd.pkg.mk"
