# $NetBSD$

GITHUB_TAG=	v${PKGVERSION_NOREV}
DISTNAME=	libvsync-4.2.0
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=open-s4c/}

MAINTAINER=	db7@sdf.org
HOMEPAGE=	https://github.com/open-s4c/libvsync/
COMMENT=	TODO: Short description of the package
LICENSE=	mit

USE_LANGUAGES=	c c++

.include "../../devel/cmake/build.mk"
#.include "../../wip/vatomic/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
